name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.X"

      - name: run checks
        run: deno task check

      - name: run tests
        run: deno task test:ci
        continue-on-error: true

      - name: upload test results
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: generate coverage report
        run: deno task coverage

      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./cov.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
